// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Image analysis AI agent.
 *
 * - analyzeImageObjects - A function that handles the image analysis process.
 * - AnalyzeImageObjectsInput - The input type for the analyzeImageObjects function.
 * - AnalyzeImageObjectsOutput - The return type for the analyzeImageObjects function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzeImageObjectsInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo to analyze, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type AnalyzeImageObjectsInput = z.infer<typeof AnalyzeImageObjectsInputSchema>;

const AnalyzeImageObjectsOutputSchema = z.object({
  objects: z.array(z.string()).describe('The objects detected in the image.'),
});
export type AnalyzeImageObjectsOutput = z.infer<typeof AnalyzeImageObjectsOutputSchema>;

export async function analyzeImageObjects(input: AnalyzeImageObjectsInput): Promise<AnalyzeImageObjectsOutput> {
  return analyzeImageObjectsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'analyzeImageObjectsPrompt',
  input: {schema: AnalyzeImageObjectsInputSchema},
  output: {schema: AnalyzeImageObjectsOutputSchema},
  prompt: `You are an expert image analyst. You will identify the objects in the image and list them.

  Image: {{media url=photoDataUri}}
  Objects: `,
});

const analyzeImageObjectsFlow = ai.defineFlow(
  {
    name: 'analyzeImageObjectsFlow',
    inputSchema: AnalyzeImageObjectsInputSchema,
    outputSchema: AnalyzeImageObjectsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
